require("plugins.config-local")
require("plugins.luasnip")

require("plugins.copilot")
require("plugins.colorthemes")

require("plugins.treesitter")

require("plugins.which-key")
require("plugins.neo-tree")
require("plugins.telescope")
require("plugins.tabby")
require("plugins.dressing")
require("plugins.gitsigns")
require("plugins.outline")
require("plugins.cmp")
require("plugins.lualine")
require("plugins.todo-comments")

require("plugins.tweaks.comment")
require("plugins.tweaks.comment")
require("plugins.tweaks.autoclose")
require("plugins.tweaks.indent-lines")
require("plugins.tweaks.colorizer")
require("plugins.tweaks.window-picker")
require("plugins.tweaks.telescope-tabs")
