# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/5bxz230k7f495x0ld7aihh9523x7hn2l-hm-session-vars.fish



status --is-login; and begin

    # Login shell initialisation


end

status --is-interactive; and begin

    # Abbreviations


    # Aliases


    # Interactive shell initialisation
    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/Users/fritiofrusck/.local/share/fish/home-manager_generated_completions" $post
    end

    /nix/store/zgqmi224w8cscysw70r39kibmwl83sag-direnv-2.32.3/bin/direnv hook fish | source


end

function __direnv_export_eval --on-event fish_prompt;
    begin;
        begin;
            "direnv" export fish
        end 1>| source
    end 2>| egrep -v -e "^direnv: export"
end;
