[package]
name = "tmux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uptime_lib = "0.2.2"
ansi_term = "0.12.1"
battery = "0.7.8"
chrono = "0.4.24"
